// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: domain/scrap/delivery/cmd/pb/scrap_delivery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScrapPBClient is the client API for ScrapPB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapPBClient interface {
	SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...grpc.CallOption) (*SendNotifyResponse, error)
}

type scrapPBClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapPBClient(cc grpc.ClientConnInterface) ScrapPBClient {
	return &scrapPBClient{cc}
}

func (c *scrapPBClient) SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...grpc.CallOption) (*SendNotifyResponse, error) {
	out := new(SendNotifyResponse)
	err := c.cc.Invoke(ctx, "/delivery.ScrapPB/SendNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapPBServer is the server API for ScrapPB service.
// All implementations must embed UnimplementedScrapPBServer
// for forward compatibility
type ScrapPBServer interface {
	SendNotify(context.Context, *SendNotifyRequest) (*SendNotifyResponse, error)
	mustEmbedUnimplementedScrapPBServer()
}

// UnimplementedScrapPBServer must be embedded to have forward compatible implementations.
type UnimplementedScrapPBServer struct {
}

func (UnimplementedScrapPBServer) SendNotify(context.Context, *SendNotifyRequest) (*SendNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotify not implemented")
}
func (UnimplementedScrapPBServer) mustEmbedUnimplementedScrapPBServer() {}

// UnsafeScrapPBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapPBServer will
// result in compilation errors.
type UnsafeScrapPBServer interface {
	mustEmbedUnimplementedScrapPBServer()
}

func RegisterScrapPBServer(s grpc.ServiceRegistrar, srv ScrapPBServer) {
	s.RegisterService(&ScrapPB_ServiceDesc, srv)
}

func _ScrapPB_SendNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapPBServer).SendNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delivery.ScrapPB/SendNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapPBServer).SendNotify(ctx, req.(*SendNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapPB_ServiceDesc is the grpc.ServiceDesc for ScrapPB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapPB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.ScrapPB",
	HandlerType: (*ScrapPBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotify",
			Handler:    _ScrapPB_SendNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/scrap/delivery/cmd/pb/scrap_delivery.proto",
}
