// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/scrap/delivery/cmd/pb/scrap_delivery.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendNotifyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotifyRequest) Reset()         { *m = SendNotifyRequest{} }
func (m *SendNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*SendNotifyRequest) ProtoMessage()    {}
func (*SendNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_081b207f3ba6a068, []int{0}
}

func (m *SendNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotifyRequest.Unmarshal(m, b)
}
func (m *SendNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotifyRequest.Marshal(b, m, deterministic)
}
func (m *SendNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotifyRequest.Merge(m, src)
}
func (m *SendNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_SendNotifyRequest.Size(m)
}
func (m *SendNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotifyRequest proto.InternalMessageInfo

type SendNotifyResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotifyResponse) Reset()         { *m = SendNotifyResponse{} }
func (m *SendNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*SendNotifyResponse) ProtoMessage()    {}
func (*SendNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_081b207f3ba6a068, []int{1}
}

func (m *SendNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotifyResponse.Unmarshal(m, b)
}
func (m *SendNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotifyResponse.Marshal(b, m, deterministic)
}
func (m *SendNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotifyResponse.Merge(m, src)
}
func (m *SendNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_SendNotifyResponse.Size(m)
}
func (m *SendNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotifyResponse proto.InternalMessageInfo

func (m *SendNotifyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*SendNotifyRequest)(nil), "delivery.SendNotifyRequest")
	proto.RegisterType((*SendNotifyResponse)(nil), "delivery.SendNotifyResponse")
}

func init() {
	proto.RegisterFile("domain/scrap/delivery/cmd/pb/scrap_delivery.proto", fileDescriptor_081b207f3ba6a068)
}

var fileDescriptor_081b207f3ba6a068 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xc9, 0xcf, 0x4d,
	0xcc, 0xcc, 0xd3, 0x2f, 0x4e, 0x2e, 0x4a, 0x2c, 0xd0, 0x4f, 0x49, 0xcd, 0xc9, 0x2c, 0x4b, 0x2d,
	0xaa, 0xd4, 0x4f, 0xce, 0x4d, 0xd1, 0x2f, 0x48, 0x82, 0x88, 0xc6, 0xc3, 0x44, 0xf5, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60, 0x7c, 0x25, 0x61, 0x2e, 0xc1, 0xe0, 0xd4, 0xbc, 0x14, 0xbf,
	0xfc, 0x92, 0xcc, 0xb4, 0xca, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x3d, 0x2e, 0x21,
	0x64, 0xc1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xe0, 0xd2, 0xe4, 0xe4,
	0xd4, 0xe2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x18, 0xd7, 0x28, 0x84, 0x8b, 0x3d,
	0x18, 0x64, 0x4d, 0x80, 0x93, 0x90, 0x27, 0x17, 0x17, 0x42, 0xab, 0x90, 0xb4, 0x1e, 0xdc, 0x62,
	0x0c, 0x5b, 0xa4, 0x64, 0xb0, 0x4b, 0x42, 0x6c, 0x53, 0x62, 0x70, 0xd2, 0x8b, 0xd2, 0xc9, 0x48,
	0x4c, 0xce, 0x4e, 0x2d, 0xca, 0x4b, 0x2d, 0xd7, 0x85, 0x7a, 0x0e, 0x8f, 0x4f, 0x93, 0xd8, 0xc0,
	0x7e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x33, 0x6d, 0xb1, 0x1c, 0x10, 0x01, 0x00, 0x00,
}
