version: '3.8'
services:
  postgres:
    image: postgres:13.4
    networks:
      - hackernew-scrap
    environment:
      POSTGRES_DB: hackernew
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
       - "5432"
  hackernew-scrap:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    networks:
      - hackernew-scrap
    ports:
      - 8088:8088
    volumes:
      - .:/hackernew-scrap
    working_dir: /hackernew-scrap/cmd
    depends_on:
      - postgres
    command: air -c .air.toml
volumes:
  postgres-data:
  hackernew-scrap:
networks:
  hackernew-scrap:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/24
          gateway: 172.168.0.1
