version: '3.8'
services:
  postgres:
    image: postgres:12
    networks:
      - hackernew-scrap
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5438:5438
  hackernew-scrap:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    networks:
      - hackernew-scrap
    working_dir: /hackernew-scrap/cmd/
    ports:
      - 8088:8088
    volumes:
      - .:/hackernew-scrap
    depends_on:
        - postgres
volumes:
  postgres-data:
  hackernew-scrap:
networks:
  hackernew-scrap:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/24
          gateway: 172.168.0.1