name: Go-ci

on:
  push:
    branches: [ "haind/test_ci" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
    - name: run lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --config=./golangci.yml --timeout=10m

